### ISSUE TITLE
ast596_2023_Spring/notes/01/week1_p1_ExploringData.ipynb Missing files

### ISSUE THREAD

**Issue by JosephKarpinski** [gnarayan/ast596_2023_Spring#90]
In [ast596_2020_Spring] you included a "Data" folder for missing files.
Is there something similar for Spring 2023 week1_p1_ExploringData.ipynb missing files;

a = pd.read_csv('tns_2023un_2459963.125990_UH88_SNIFS_SCAT.dat',\
                sep=' ', names=['wave','flux','fluexerr'], comment='#')
b = pd.read_csv('tns_2023wl_2023-01-20_07-36-09_SOAR_Goodman_UCSC.flm',
                sep=' ', names=['wave','flux','fluexerr'], comment='#')
c = pd.read_csv('tns_2023yv_2023-01-22_11-28-59.764590_P60_SEDM_ZTF.ascii',
                sep=' ', names=['wave','flux','fluexerr'], comment='#')

Thanks!

**Comment by gnarayan** [comment]
These are just spectra from the transient name server (TNS - https://www.wis-tns.org/). I usually just download ones that are uploaded around the week I'm doing the lecture.
